### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [2]:
pip install torch

Note: you may need to restart the kernel to use updated packages.


In [2]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [3]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換


# 建立 numpy ndarray
a = np.random.rand(2,2,3)
print("\na", a)
print(f'a: {type(a)}, {a.dtype}')

# 建立 torch tensor from ndarray
b = torch.from_numpy(a)
print("\nb", b)
print(f'b: {type(b)}, {b.dtype}')

# 建立 torch tensor
c = torch.tensor(a)
print("\nc", c)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()

print(f'd: {type(d)}, {d.dtype}')


a [[[0.29096128 0.65152254 0.98827087]
  [0.47413234 0.69209088 0.19274741]]

 [[0.64969813 0.39323054 0.8680702 ]
  [0.87779926 0.40106532 0.6618064 ]]]
a: <class 'numpy.ndarray'>, float64

b tensor([[[0.2910, 0.6515, 0.9883],
         [0.4741, 0.6921, 0.1927]],

        [[0.6497, 0.3932, 0.8681],
         [0.8778, 0.4011, 0.6618]]], dtype=torch.float64)
b: <class 'torch.Tensor'>, torch.float64

c tensor([[[0.2910, 0.6515, 0.9883],
         [0.4741, 0.6921, 0.1927]],

        [[0.6497, 0.3932, 0.8681],
         [0.8778, 0.4011, 0.6618]]], dtype=torch.float64)
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [4]:
t1 = torch.tensor([1,2,3])
print("t1:{}".format(t1))
print(t1.shape)
print(torch.is_tensor(t1))

t2 = torch.zeros(1)
print("t2:{}".format(t2))

t3 = torch.zeros([2,3,4])
print("t3:{}".format(t3))

t4 = torch.ones([2,2,3])
print("t4:{}".format(t4))

t1:tensor([1, 2, 3])
torch.Size([3])
True
t2:tensor([0.])
t3:tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
t4:tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [5]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int32
b: <class 'torch.Tensor'>, torch.int32
c: <class 'torch.Tensor'>, torch.int32
d: <class 'numpy.ndarray'>, int32


### Function 1 - torch.from_numpy() / tensor.numpy()

In [6]:
# torch.from_array() => 將 numpy 的 ndarray 傳換成 tensor 格式

q1=np.ndarray([1,2,3])
print(q1)
print(q1.shape)
print(q1.dtype)

q_1=torch.from_numpy(q1)
print(q_1)
print(q_1.shape)
print(q_1.dtype)


[[[0. 0. 0.]
  [0. 0. 0.]]]
(1, 2, 3)
float64
tensor([[[0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)
torch.Size([1, 2, 3])
torch.float64


In [7]:
# tensor.numpy() => 將 tensor 格式轉換成 ndarray 格式
q2=q_1.numpy()
print(q2)
print(q2.shape)
print(q2.dtype)


[[[0. 0. 0.]
  [0. 0. 0.]]]
(1, 2, 3)
float64


### Function 2 - torch.unsqueeze() / torch.squeeze()

In [8]:
# torch.unsqueeze() => 擴充某一個維度


q0=torch.from_numpy(np.ndarray([2,1]))
print(q0)
print(q0.shape)

# 維度1 => 壓縮
q_0_s=torch.squeeze(q0,1)
print("\n:壓縮維度1",q_0_s)
print(q_0_s.shape)

q_0=torch.unsqueeze(q0,2)
print("\n擴充維度2",q_0)
print(q_0_s.shape)

q_1
print("\n",q_1)
print(q_1.shape)
q_2=torch.unsqueeze(q_1, 2)
print("\n",q_2)
print(q_2.shape)

# shape : [1,2,3] => 變成 [1,2,1,3]



tensor([[ 9.9447e-259],
        [-5.2655e+285]], dtype=torch.float64)
torch.Size([2, 1])

:壓縮維度1 tensor([ 9.9447e-259, -5.2655e+285], dtype=torch.float64)
torch.Size([2])

擴充維度2 tensor([[[ 9.9447e-259]],

        [[-5.2655e+285]]], dtype=torch.float64)
torch.Size([2])

 tensor([[[0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)
torch.Size([1, 2, 3])

 tensor([[[[0., 0., 0.]],

         [[0., 0., 0.]]]], dtype=torch.float64)
torch.Size([1, 2, 1, 3])


In [9]:
q0

tensor([[ 9.9447e-259],
        [-5.2655e+285]], dtype=torch.float64)

### Function 3 - tensor.transpose() / tensor.permute()

In [35]:
# tensor.transpose() => 將 tensor 依照輸入的 "二" 個維度轉置

### your code ###
input_x = torch.randint(100,[2,2,3])
print("input_x", input_x)
output_x=torch.transpose(input_x,0,1)
print("q0_trans:{}".format(output_x))


input_x tensor([[[74, 75, 59],
         [59, 90, 10]],

        [[44, 63, 58],
         [51,  8, 38]]])
q0_trans:tensor([[[74, 75, 59],
         [44, 63, 58]],

        [[59, 90, 10],
         [51,  8, 38]]])


In [42]:
#  tensor.permute() => 將 tensor 依照輸入的 "多個" 維度轉置

### your code ###
input_x = torch.randint(100,[2,2])
print(input_x)

# 2nd arg 的維度必須與 tensor 的維度一致
output_x = torch.permute(input_x, [0, 1])
print(output_x)


### your code ###
input_x = torch.randint(100,[2,2,3])
print(input_x)

# 2nd arg 的維度必須與 tensor 的維度一致
output_x = torch.permute(input_x, [0, 1, 2])
print(output_x)

### your code ###
input_x = torch.randint(100,[2,2,3,4])
print(input_x)

# 2nd arg 的維度必須與 tensor 的維度一致
output_x = torch.permute(input_x, [0, 1, 2, 3])
print(output_x)

tensor([[98, 21],
        [67, 84]])
tensor([[98, 21],
        [67, 84]])
tensor([[[78, 43, 46],
         [16, 28, 34]],

        [[70, 13, 23],
         [89, 88, 40]]])
tensor([[[78, 43, 46],
         [16, 28, 34]],

        [[70, 13, 23],
         [89, 88, 40]]])
tensor([[[[98, 12, 55,  6],
          [72,  7, 66, 72],
          [56, 36, 93, 63]],

         [[87, 76, 96, 68],
          [ 2, 40,  0, 66],
          [64, 75, 85, 46]]],


        [[[11, 44, 67, 94],
          [32, 28, 28, 64],
          [12, 95, 82, 61]],

         [[33,  4, 23, 75],
          [90, 49, 42, 73],
          [16, 41, 50, 78]]]])
tensor([[[[98, 12, 55,  6],
          [72,  7, 66, 72],
          [56, 36, 93, 63]],

         [[87, 76, 96, 68],
          [ 2, 40,  0, 66],
          [64, 75, 85, 46]]],


        [[[11, 44, 67, 94],
          [32, 28, 28, 64],
          [12, 95, 82, 61]],

         [[33,  4, 23, 75],
          [90, 49, 42, 73],
          [16, 41, 50, 78]]]])


### Function 4 - torch.reshape() / tensor.view()

In [44]:
# torch.reshape()  => 重塑 tensor

### your code ###
input_x=torch.randint(100,[2,2])
print("input_x:",input_x)

output_x=torch.reshape(input_x,(-1,))
print("output_x:",output_x)

input_x: tensor([[57, 67],
        [70, 47]])
output_x: tensor([57, 67, 70, 47])


In [64]:
# tensor.view() => 依照輸入的維度 轉置 tensor
### your code ###

input_x=torch.randint(100,[2,2])
print("input_x:",input_x)
# 輸入的 size 乘機 必須與 tensor 的維度乘機相等: 2x2 = 1x4
output_view=input_x.view(1,4)
print(output_view)


# 輸入的 size 乘機 必須與 tensor 的維度乘機相等: 3x3x2 = 1x1x18
input_x=torch.randint(50,[3,3,2])
print("input_x:",input_x)
output_x=input_x.view(1,1,18)
print("output_x:",output_x)
output_x=input_x.view(2,9,1)
print("output_x:",output_x)





input_x: tensor([[53, 49],
        [73, 87]])
tensor([[53, 49, 73, 87]])
input_x: tensor([[[44, 46],
         [ 1, 38],
         [48, 35]],

        [[29, 48],
         [17,  5],
         [46,  6]],

        [[47,  7],
         [26, 39],
         [21, 32]]])
output_x: tensor([[[44, 46,  1, 38, 48, 35, 29, 48, 17,  5, 46,  6, 47,  7, 26, 39, 21,
          32]]])
output_x: tensor([[[44],
         [46],
         [ 1],
         [38],
         [48],
         [35],
         [29],
         [48],
         [17]],

        [[ 5],
         [46],
         [ 6],
         [47],
         [ 7],
         [26],
         [39],
         [21],
         [32]]])
